---
title: "Notas_Tema_9_Agrupar_Datos"
author: "antonio"
date: "22/1/2021"
output: html_document
---


```{r}
#Importamos el data frame datacrab y arreglemos los datos.
cangrejo= read.table("C:/Users/anton/OneDrive/Documents/Cursos/Estadistica descriptiva R y Python/Repositorio/curso_r_basico/data/datacrab.txt",header = TRUE);
head(cangrejo)
str(cangrejo) #Aplicamos la función summary
cw= cangrejo$width  #Tomamos la anchura porque es la unica variabe numerica con decimales

#REGLA 1.CALCULAMOS EL NUMERO DE CLASES 
n=length(cw)
#Regla de la raiz cuadrada (calcular el numero de clases)
k1=ceiling(sqrt(n))  
k1  #R= 14 intervalos

#Regla de Sturges
k2= ceiling(1+log(n,2)) 
k2   #R= 9 intervalos

#Regla de scott
As = 3.5*sd(cw)*n^(-1/3) #Amplitud teórica
k3 = ceiling(diff(range(cw))/As)  #
k3   #R= 10 intervalos

#Regla de Freedman-Diaconis: Amplitud teórica
Afd = 2*(quantile(cw,0.75, names = FALSE)-quantile(cw,0.25,names = FALSE))*n^(-1/3) #names=FALSE regresa el Cuartil en numero sin encabezado
k4 = ceiling(diff(range(cw))/Afd)
k4      #R= 13 intervalos

#Comprobamos el Num. Intervalos resultantes utilizando las funciones propias de "R"
nclass.Sturges(cw)  #R= 9  intervalos
nclass.scott(cw)  #R= 10 intervalos
nclass.FD(cw)   #R=13 intervalos

#REGLA 2.CALCULAMOS LA AMPLITUD DE LOS INTERVALOS
A=diff(range(cw))/10   
A  
#R= 1.25 (donde "A" es la amplitud teorica)
#A= 1.3 para ser consistente con la amplitud, redondeamos por exceso para ser mas exacto con los datos
#y evitar caer en error al elegir las marcas de clase, y asi se evita que los datos caigan en los extremos

#NOTA: Recordar que si el cociente nos hubiera dado un valor exacto con respecto a la precision, tendriamos que haberle sumado una unidad a la precision

#range(<df>)= calcula el Valor_minimo-Valor_maximo del conjunto de datos
#diff(<dd>) = Hace la resta de cada elemento del vetor de E.1-.E.2, E.2-E.3, hasta E.n-1 - E_n_elementos
#ceiling(<>)= Redondea al numero entero mas cercano


#REGLA 3.CALCULAMOS LOS EXTREMOS DE LOS INTERVALOS
#Ya sabemos que los extremos iran de 1.3 en 1.3

L1=min(cw)-1/2*0.1 #Calculamos el primer extremo del intervalo (con esto se obtiene el primer intervalo) 
L1   #R=20.95
#Donde 0.1 es nuestra precision (decimal de unidad en este caso) y A es la amplitud

#Intervalos
L2 = L1 + A
L3 = L2 + A
L4 = L3 + A
L5 = L4 + A
L6 = L5 + A
L7 = L6 + A
L8 = L7 + A
L9 = L8 + A
L10 = L9 + A
L11 = L10 + A
L = c(L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11)   #Concatenamo los intervalos 
L
#Ninguno de los extremos del intervalo caera entre los intervalos simplemente por construccion del algoritmo

L = L1 + A*(0:10) #Otra forma: Intervalo mas la amplitud miltiplicada desde 0:10 
L 

#REGLA 4.CALCULAMOS LA MARCA DE CLASE (Punto medio de cada uno de los intervalo)
X1 = (L[1]+L[2])/2
X1  #R1= 21.6

#4.INTERVALOS MARCA DE CLASE 
X2 = X1 + A
X3 = X2 + A
X4 = X3 + A
X5 = X4 + A
X6 = X5 + A
X7 = X6 + A
X8 = X7 + A
X9 = X8 + A
X10 = X9 + A
X = c(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10) #CENTRO GEOMETRICO ES IGUAL A LA MARCA DE CLASE "X1"
X

X=X1+A*(0:9)  #Otra forma : Intervalos de clase con sucesion
X

X = (L[1:length(L)-1]+L[2:length(L)])/2 #Otra forma : Como punto medio del intervalo
X

```


# Estadisticos para datos agrupádos


```{r}
#Esta funcion se tomo del Notas_9_agrupar_datos_II par complementar el tema del ejercicion y darle
#continuidad al tema ya que se requieren como complemento para el calculo de los D.Agupados


TablaFrecs = function(x,k,A,p){ 
  L = min(x)-p/2+A*(0:k) #Extremo de los intervalos
  x_cut = cut(x, breaks = L, right=FALSE) #Dividir los datos x en intervalos, right=FALSE(sin cerrar por la derecha)
  intervals = levels(x_cut) #Obtenermos los Dif. intervalos como los niveles de la variable x_cut
  mc = (L[1]+L[2])/2+A*(0:(k-1))  #Puntomedio de los intervalos
  Fr.abs = as.vector(table(x_cut)) #Frec Abs
  Fr.rel = round(Fr.abs/length(x),4) #Frec Rel
  Fr.cum.abs = cumsum(Fr.abs)  #Frec Abs Acum
  Fr.cum.rel = cumsum(Fr.rel)  #Frec Rel Acum
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)#Todos los datos se pasan a un dataframe
  tabla
}


```


#Calcular las medidas de Tendencia central y Medias de Dispersion en D.Agrupados
#calcular los estadísticos de la variable datos agrupados y, para acabar, estimaremos la mediana y algunos cuantiles.
```{r}
#Tabla de frec primera funcion
tabla=TablaFrecs(cw,k=10,A=1.25, p=0.1)
tabla



tabla$intervals


TOT = tabla$Fr.cum.abs[10]
TOT  #Total del universo

anchura.media= round(sum(tabla$Fr.abs*tabla$mc)/TOT,3  )
anchura.media #Media de datos agrupados

anchura.var = round(sum(tabla$Fr.abs*tabla$mc^2)/TOT-anchura.media^2,3)
anchura.var #Varianza de datos agrupados

anchura.dt = round(sqrt(anchura.var),3)
anchura.dt #Desviación típica

I.modal = tabla$intervals[which(tabla$Fr.abs == max(tabla$Fr.abs))]
I.modal #Intervalo modal, valor con mayor frecuencia

I.critic = tabla$intervals[which(tabla$Fr.cum.rel >= 0.5)]
I.critic[1] #Intervalo critico, Acceder a la tabla de intervalos y buscar el primer valor que supera el 0.5% de los datos

#Ahora, ya podemos calcular una estimación de la mediana de los datos “reales”.

n = TOT   #Total de elementos de la muestra
Lc = L[4]  #Limite inferior
Lc.pos = L[5] #limite superior
Ac = L[5]-L[4] # Amplitud de los limites
Nc.ant = tabla$Fr.cum.abs[3] #Frecuencia Abs.Acum anterior (Lc)
nc = tabla$Fr.abs[4]  #Frecuencia Absoluta del intervalo critico

M = Lc+Ac*((n/2)-Nc.ant)/nc
M #Aproximación de la mediana de los datos "reales" se calcula con todos los calculos anteriores

median(cw) #Mediana de los datos "reales" sin agrupar


#funcion para el calculo de los cuantiles
aprox.quantile.p = function(Lcrit,Acrit,n,p,Ncrit.ant,ncrit){
  round(Lcrit+Acrit*(p*n-Ncrit.ant)/ncrit,3)
}
aprox.quantile.p(Lc,Ac,n,0.25,Nc.ant,nc) #Primer cuartil
aprox.quantile.p(Lc,Ac,n,0.75,Nc.ant,nc) #Tercer cuartil

#calculemos los cuartiles de los datos “reales”
quantile(cw,0.25)
quantile(cw,0.75)
```


#HISTROGRAMAS DE LOS CANGREJOS 

```{r}
L = L1 + A*(0:10) #Otra forma: Intervalo mas la amplitud miltiplicada desde 0:10 
L 
hist(cw, breaks = "Sturges" , right = FALSE, main = "Histograma de las anchuras de los cangrejos")
hist(cw, breaks = "Sturges", right = FALSE, plot = FALSE)
```
