---
title: "Notas_Tema_6_Multi"
author: "antonio"
date: "24/10/2020"
output: html_document
---

# Tablas de frecuencias multidimencionales
## Ejemplo con 3 dimensiones 
```{r}
ans= sample(c("SI","NO"), size=100, replace= TRUE)
sex= sample(c("H","M"), size=100, replace= TRUE)
place= sample(c("san francisco","barcelona","madrid", "valencia","betis"), size=100, replace= TRUE)

table(sex,ans,place) #Muestra una tabla frecuencia absoluta de los datos
#Tabla en formato de datos cruzados 
ftable(sex,ans,place)
#Tabla en formato cruzado donde la columnas son: sex,ans
ftable(sex,ans,place,col.vars = c("sex","ans"))
```

### Filtrado de tablas/Frecuencia Abs

<!-- ```{r} -->
<!-- table(sex, ans, place)["M", "SI", "barcelons"] -->
<!-- table(sex, ans, place)[ , "Si", "madrid"] -->
<!-- table(sex, ans, place)[ , "NO", ] -->
<!-- table(sex, ans, place)["M", , "valencia"] -->
<!-- ``` -->


### Frecuencias relativas 
```{r}
prop.table(table(sex, ans, place))#Frec. Rel. Globales
prop.table(table(sex, ans, place), margin = 3) # Frec. Rel. Marginal por Lugar
prop.table(table(sex, ans, place), margin = c(1, 3)) # Frec. Rel. Marg. por Sexo y País

ftable(prop.table(table(sex, ans, place)))
```

#Ejamplo con datos PEOPLE (Objeto de datos agreagados)


```{r}
#Es un objeto de tipo dataframe pero agrupado como tabla multidimensional 
HairEyeColor
#Aplicamos la funcion sum() , para obtener el total de regitros de la tabla
sum(HairEyeColor) -> total
```

El total de individuos de la tabla de datos es `r total`.

```{r}
#Frecuencia marginar  de la viata SEX
prop.table(HairEyeColor, margin = 3)
#Frecuencia marginar  de la viata HAIR , EYES
prop.table(HairEyeColor, margin = c(1,2))
```

```{r}
#permite cambiar el orden de las columnas  pasándole como parámetro el orden de las columna
aperm(HairEyeColor, perm = c("Sex", "Hair", "Eye"))
```

```{r}
#Esta libreria muestrA el objeto de datos en formato tabla (el datafreme antes del agrupado).
library(kableExtra)
kable(HairEyeColor)
```

```{r, results='asis'}
library(xtable)
sex = factor(c("H", "M", "M", "M", "H", "H", "M", "M"))
ans = factor(c("S", "N", "S", "S", "S", "N", "N", "S"))
#Solo aplica para tabla de dos dimensiones 
xtable(table(sex, ans))
```



### Ejemplo de EnergyDrink

```{r}
Beb_Energ=read.table("C:/Users/anton/OneDrive/Documents/Cursos/Estadistica descriptiva R y Python/Repositorio/curso_r_basico/data/EnergyDrink",header=TRUE)
#Mostramos el layout del dataframe
str(Beb_Energ)
# Mostramos las primeras 5 filas del dataframe
head(Beb_Energ,5)
# La funcion summary permite obtener un resumen de con las frecuencias absolutas de cada variable
summary(Beb_Energ)
#Creamos la tabla de las frecuencias absolutas para cada una de las variables por separado 
apply(Beb_Energ, MARGIN=2, FUN=table)
#Calculamos la tabla de frecuencias absolutas de la columna sexo
table(Beb_Energ$sexo)
#Si aplicamos la funcion table(<dataframe>) a un df,que solo contenga variable cualitativas
#obtendemos el resumen de las frecuencias absolutas
table(Beb_Energ)
#Obtenermos la tabla defrecuencias absolutas del dataframe pero en formato plano-multidimensional
ftable(Beb_Energ)

```



