---
title: "Tarea_12_ED_Datos_cuantitativos"
author: "antonio"
date: "17/1/2021"
output: html_document
---

```{r}
grados= read.table("C:/Users/anton/OneDrive/Documents/Cursos/Estadistica descriptiva R y Python/Repositorio/curso_r_basico/data/grades.txt",header=TRUE)
str(grados)

```

##  MEDIDAS DE DISPERSION POR ESTUDIO UNIVERSITARIO
```{r}
#summary(grados)
#Medias 
media= aggregate(nota~estudio, data=grados, FUN=mean)
media$nota=round(media$nota,2)
names(media)<-c("ESTUDIO", "MEDIA")
media

mediana= aggregate(nota~estudio,data=grados, FUN=median)
mediana$nota=round(mediana$nota,2)
names(mediana)<-c("ESTUDIO", "MEDIANA")
mediana

datos <- function(col1,df){
    val1= df[df$estudio == col1 ,]
    val=sort(round(val1$nota,2))
    moda=as.numeric( names( which(table(val)== max(table(val))) )) #Calculamos la  moda
    #print(val)
    #print( col1 )
    #print( mod )
    data.frame(ESTUDIO=col1,MODA=moda)
}

Mod1=datos ("Industrial",grados)
Mod2=datos ("Informatica",grados)
Mod3=datos ("Mates",grados)
Mod4=datos ("Telematica",grados)
moda = rbind(Mod1,Mod2,Mod3,Mod4)
moda

```

##  MEDIDAS DE DISPERSION CONJUNTAS

```{r}
mean(round(grados$nota,2) )   #Media
median(round(grados$nota,2) ) #Mediana
as.numeric( names( which(table(round( grados$nota,2))== max(table(round( grados$nota,2)))) )) #moda
```

```{r}
boxplot(nota~estudio,data=grados, main="Boxplot Notas de Examenes", ylab="Notas", xlab="Examen",col=c("yellow","green","lightblue","cyan"),notch=TRUE )
points(media,col="red",pch=22 )
```








