---
title: "Notas_Tema_11_Distribucion_Poisson"
author: "antonio"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Distribución de Poisson

Supongamos que $X$ modela el número de errores por página que tiene un valor esperado $\lambda = 5$.

## En `R`
```{r}
l = 5  # Lamda = media o valore esperado
dpois(x= 0:10,lambda = l) #Distribucion de las probabilidades de 0 a 10 paginas 
plot(0:20, dpois(x = 0:20, lambda = l)) #Calculamos la Distribucion de las probabilidades de 0 a 20 paginas

ppois(0:20, l) #Distribucion de probabilidad acumulada 
qpois(0.5, 5)  #Mediana de una poisson, que esta es el mismo valor de la lamda o media

#Tomamos una 1000 paginas de manera aleatoria y calculamos la probabilidad de numero de errores por cada una
rpois(1000, lambda = l) -> data
#Con los 1000 datos aleatorios ahora graficamos con un histigrama esos resultados
hist(data)
```


# Ejemplo Acesor Banco
En un banco un acesor comercial atiende en promedioa 3 personas or hora, ¿Cual es la probabilida 
de ue en la siguiente hora atienda solmanente a 2 personas?
$\lambda = 3$. .... $x=2$

```{r}
L= 3 #Promedio de eventos
X= 2 #Numero de exitos que suceden 
dpois(x=X,lambda = L)
dpois(0:5, lambda = L) #Distribucion de probabilidad acumulada 
plot(0:5, ppois(0:5, lambda = L),ylim=c(0,1)) #Distribucion de probabilidad acumulada 
```



## En `Python`

```{python}
import numpy as np
from scipy.stats import poisson #Paquque para trabajar con la funcion de poisson
import matplotlib.pyplot as plt


fig, ax = plt.subplots(1,1)  #Creaos un objeto de ripo figura 
mu = 5   # Lamda = media o valore esperado
#Observamos los patametros media,varianza,sesgo,curtosis, con ayuda de la funcion "stats"
mean, var, skew, kurt = poisson.stats(mu, moments = 'mvsk')  
print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)

x = np.arange(0, 12)  #Generamos numeros entre 0-12
#ax.plot(<las x>,poisson.pmf(x, mu), < 'bo' = bolitas azules>, < ms = 8,><label="Etiqueta">)
ax.plot(x, poisson.pmf(x, mu), 'bo', ms = 8, label = 'Poisson(0.8)')
#Pintamoa las rayas verticales 
ax.vlines(x,0, poisson.pmf(x,mu), colors = 'b', lw = 4, alpha = 0.5)
ax.legend(loc = "best", frameon = False)
plt.show()


#Interpretacion: mu = 8
#1. La media coincide con el parametro landa  8.000000
#2. El sesgo es positivo por que los datos estan a la izquierda 
#3. Curtosis positiva


#Interpretacion: mu = 5
#1. La media coincide con el parametro lamda  5.000000
#2. El sesgo es positivo por que los datos estan ligeramente a la izquierda 
#3. Curtosis es redonda similar a una distribucioin normal 

```

