---
title: "Trabajando con R y Python"
author: "antonio"
date: "7/7/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate

```{r}
#utilizamos una libreria de Python en R
library(reticulate)
use_python("C:/Users/anton/.conda/pkgs/python-3.7.7-h81c818b_4") 
use_python("C:/Users/anton/AppData/pkgs/python-3.7.7-h81c818b_4")
#Carga los paquetes de la instalacion de anaconda par pode rser utilizados en R
#py_install("nombre del paquete a instalar")   # Instalar un paquete faltante
os = import("os")  # Acceder a las libreria sde python en R
os$listdir(".")    # Listael contenido del directorio de trabajo

```


#Ejecutar una funcion de python en R con la funcion source_python
```{r}
source_python("cuadrado.py")
multiplicacion(3,3)
```


```{r}
# conversion de objetos de un lenguaja a otro

np = import("numpy", convert =FALSE)  #Para trabajar objetos nativos de python
x= np$array(c(1:4))
sum = x$cumsum()

#imprimir la lista de numeros nativa python creada en R
print(sum)

#Conversion explicita de R a Python
py_to_r(sum)
```


## Opcion Ayuda
```{r}
#Para consultar la documentacion como R o Python las conversiones Reticulate son en automaticas por que el interprete las palica
py_help(os$chdir)
help(py_to_r)
```


## Array

```{r}
#Declarando un array
#Creamos un array objeto python , la opcion order=C (utiliza opcion de guardado en en memoria de "C" en lugar estilo de guardado  de "fortra"), para optimizar el manejo de los datos  
a <- np_array(c(1:10), dtype="float16", order="C")
a
```


```{r}

datos <- iris
head(datos)
#Convertimos el objeto datos a Python para manipularlo en codigo Python
datos_py <- r_to_py (datos) #Del data frame de R pasamos a Python con r_to_py 

```
 


```{python}
#import numpy as np
#import pandas as pd
#r.datos_py.head()
```





```{r}
library(Matrix)
N=6
set.seed(123)
sparse_mat -> sparseMatrix(
  
  i=sample(N,N,replace = F),
  j=sample(N,N,replace = F),
  x=runif(N),
  dims=c(N,N)
)

sparse_mat
sparse_mat_py=r_to_py(sparse_mat)
```


```{python}
r.sparse_mat_py
```

```{r}
py_to_r(sparse_mat_py)
```




